### ISSUE TITLE
May I fork this page to use for my own tensegrity robotics paper archive?

### ISSUE THREAD

**Issue by jrieffel** [quality-diversity/quality-diversity.github.io#8]
Again, subject says it all.

Bisous,
jr

**Comment by Aneoshun** [comment]
Hi @jrieffel 
I guess this has been solved. 
Closing the issue.

**Comment by jrieffel** [comment]
I never actually got an answer :(

**Comment by Aneoshun** [comment]
Ahh sorry! I read the title too fast and thought it referred to uploading papers, and as you successfully managed to do it I thought it was an outdated comment. 

Sure thing! If you want to use this page to make your own archive, please do!

**Comment by Aneoshun** [comment]
I re-opened the issue in case you have any questions related to the code. Feel free to close it when you want.

**Comment by jrieffel** [comment]
merci! Tu est trop gentil!
